Repository karmada-io/community, pull requests merged in 2022-10, with the labels that each got.

#11 Add security docs for Karmada
  .github/ISSUE_TEMPLATE/distributors-application.md
  security-team/README.md
  security-team/SECURITY.md
  security-team/comms-templates/distributors-announcement-email.md
  security-team/comms-templates/join-announcement-email-list.md
  security-team/comms-templates/non-vuln-response.md
  security-team/comms-templates/vulnerability-announcement-email.md
  security-team/comms-templates/vulnerability-announcement-issue.md
  security-team/images/Vulnerability-handling-process.PNG
  security-team/images/vulnerability-process-timeline.PNG
  security-team/private-distributors-list.md
  security-team/report-a-vulnerability.md
  security-team/security-groups.md
  security-team/security-release-process.md
Labels: size/XL, lgtm, kind/documentation, approved

#15 Add reviewers.md
  REVIEWERS.md
Labels: size/M, lgtm, kind/documentation, approved

#13 Add 2022-annual-review docs
  cncf_process/2022_karmada_annual/2022-karmada-annual.md
  cncf_process/2022_karmada_annual/images/contributors.png
Labels: lgtm, kind/documentation, approved, size/L

#17 Update the picture and fix typos
  cncf_process/2022_karmada_annual/2022-karmada-annual.md
  cncf_process/2022_karmada_annual/images/contributors.png
Labels: kind/cleanup, lgtm, size/XS, approved

#18 Update annual review content
  cncf_process/2022_karmada_annual/2022-karmada-annual.md
Labels: size/S, lgtm, kind/documentation, approved
