Repository karmada-io/community, pull requests merged in 2023-07, with the labels that each got.

#39 add windsonsea to doc-reviewer
  REVIEWERS.md
Labels: lgtm, kind/documentation, size/XS, approved

#40 Add maintainers definition
  community-membership.md
Labels: size/M, lgtm, kind/documentation, approved

#43 Edit reviewers
  APPROVERS.md
  REVIEWERS.md
  contributors/guide/owners.md
Labels: size/M, lgtm, kind/documentation, approved

#44 Add maintainer to reviewer and approver
  APPROVERS.md
  REVIEWERS.md
Labels: lgtm, kind/documentation, approved, size/L

#47 Modify affiliation
  APPROVERS.md
  REVIEWERS.md
Labels: lgtm, size/XS, approved

#45 Propsing project governance
  GOVERNANCE.md
Labels: kind/cleanup, size/M, lgtm, approved
