Repository karmada-io/community, pull requests merged in 2025-01, with the labels that each got.

#96 Add talk from KubeCon India
  talks/README.md
Labels: lgtm, kind/documentation, size/XS, approved

#92 Add Huawei to Private Distributors List
  security-team/security-groups.md
Labels: lgtm, size/XS, approved

#98 Add DaoCloud to Private Distributors List
  security-team/security-groups.md
Labels: lgtm, size/XS, approved

#99 Update community meeting time
  README.md
Labels: lgtm, kind/documentation, size/XS, approved

#100 Add issue template for adopter group application
  .github/ISSUE_TEMPLATE/adopter-group-application.yaml
Labels: size/M, lgtm, kind/documentation, approved

#95 Proposing Karmada Adopter Group
  adopter-group/README.md
Labels: lgtm, kind/documentation, approved, size/L
