Repository karmada-io/community, pull requests merged in 2025-05, with the labels that each got.

#133 Add CECloud to Private Distributors List
  security-team/security-groups.md
Labels: lgtm, size/XS, approved

#135 Update adopter onboarding application template
  .github/ISSUE_TEMPLATE/adopter-onboarding.md
Labels: kind/cleanup, size/M, lgtm, approved

#138 add maintainers
  MAINTAINERS.md
Labels: size/S, lgtm, kind/documentation, approved
