Repository karmada-io/community, pull requests merged in 2025-03, with the labels that each got.

#110 add MAINTAINERS.md
  MAINTAINERS.md
Labels: size/S, lgtm, kind/documentation, approved

#113 Update adopter group application form to track process
  .github/ISSUE_TEMPLATE/adopter-group-application.yaml
Labels: size/S, lgtm, kind/documentation, approved

#112 Add maintainership change rule
  community-membership.md
Labels: size/M, lgtm, kind/documentation, approved

#118 Add subprojects documentation
  GOVERNANCE.md
Labels: size/S, lgtm, kind/documentation, approved

#117 Add Roadmap change process documentation
  GOVERNANCE.md
Labels: size/S, lgtm, kind/documentation, approved

#114 Propose Karmada roadmap of year 2025
  ROADMAP.md
Labels: size/M, lgtm, kind/documentation, approved

#121 Archive security audit report
  security-team/assessments/OSTIF-Karmada-Report.pdf
  security-team/assessments/README.md
Labels: size/S, lgtm, kind/documentation, approved

#120 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: lgtm, kind/documentation, size/XS, approved
